[install]
peer = true
hoistPattern = ["*"]
production = false

[install.cache]
dir = ".bun/cache"
disable = false

[test]
coverage = true

[debug]
enabled = false

[test]
preload = ["./test.setup.ts"]