services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_PRISMA_URL=postgresql://postgres:postgres@db:5432/mydatabase?pgbouncer=true&connection_limit=1
      - POSTGRES_URL_NON_POOLING=postgresql://postgres:postgres@db:5432/mydatabase
    env_file:
      - .env.local
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: